Remove redundant call The call was causing an exception as of at least python 3.13, potentially earlier.
```
Traceback (most recent call last):
  File "/usr/bin/base16-shell-preview", line 33, in <module>
    sys.exit(load_entry_point('base16-shell-preview==1.0.0', 'console_scripts', 'base16-shell-preview')())
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/base16_shell_preview/__main__.py", line 294, in main
    curses.wrapper(
    ~~~~~~~~~~~~~~^
        run_curses_app, base16_shell_dir.joinpath('scripts'), args.sort_bg)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/curses/__init__.py", line 101, in wrapper
    endwin()
    ~~~~~~^^
_curses.error: endwin() returned ERR
```